const userSeed = [{
  "id": 1,
  "spotifyUsername": "ffasey0",
  "accessToken": "lolollollol",
  "refreshToken": "kevindurant"
}, {
  "id": 2,
  "spotifyUsername": "rbarthrop1",
  "accessToken": "lolollollol",
  "refreshToken": "kevindurant"
}, {
  "id": 3,
  "spotifyUsername": "omatlock2",
  "accessToken": "lolollollol",
  "refreshToken": "kevindurant"
}, {
  "id": 4,
  "spotifyUsername": "khandley3",
  "accessToken": "lolollollol",
  "refreshToken": "kevindurant"
}, {
  "id": 5,
  "spotifyUsername": "cberrey4",
  "accessToken": "lolollollol",
  "refreshToken": "kevindurant"
}, {
  "id": 6,
  "spotifyUsername": "locarroll5",
  "accessToken": "lolollollol",
  "refreshToken": "kevindurant"
}, {
  "id": 7,
  "spotifyUsername": "dquarrell6",
  "accessToken": "lolollollol",
  "refreshToken": "kevindurant"
}, {
  "id": 8,
  "spotifyUsername": "ldevlin7",
  "accessToken": "lolollollol",
  "refreshToken": "kevindurant"
}, {
  "id": 9,
  "spotifyUsername": "ocoultard8",
  "accessToken": "lolollollol",
  "refreshToken": "kevindurant"
}, {
  "id": 10,
  "spotifyUsername": "spiborn9",
  "accessToken": "lolollollol",
  "refreshToken": "kevindurant"
}]

module.exports = userSeed
